/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StationsRouteImport } from './routes/stations'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StationIdRouteImport } from './routes/station_.$id'
import { Route as StationIdMapRouteImport } from './routes/station_.$id_.map'

const StationsRoute = StationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StationIdRoute = StationIdRouteImport.update({
  id: '/station_/$id',
  path: '/station/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StationIdMapRoute = StationIdMapRouteImport.update({
  id: '/station_/$id_/map',
  path: '/station/$id/map',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/safety': typeof SafetyRoute
  '/stations': typeof StationsRoute
  '/station/$id': typeof StationIdRoute
  '/station/$id/map': typeof StationIdMapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/safety': typeof SafetyRoute
  '/stations': typeof StationsRoute
  '/station/$id': typeof StationIdRoute
  '/station/$id/map': typeof StationIdMapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/safety': typeof SafetyRoute
  '/stations': typeof StationsRoute
  '/station_/$id': typeof StationIdRoute
  '/station_/$id_/map': typeof StationIdMapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/safety'
    | '/stations'
    | '/station/$id'
    | '/station/$id/map'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/safety'
    | '/stations'
    | '/station/$id'
    | '/station/$id/map'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/safety'
    | '/stations'
    | '/station_/$id'
    | '/station_/$id_/map'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SafetyRoute: typeof SafetyRoute
  StationsRoute: typeof StationsRoute
  StationIdRoute: typeof StationIdRoute
  StationIdMapRoute: typeof StationIdMapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stations': {
      id: '/stations'
      path: '/stations'
      fullPath: '/stations'
      preLoaderRoute: typeof StationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/station_/$id': {
      id: '/station_/$id'
      path: '/station/$id'
      fullPath: '/station/$id'
      preLoaderRoute: typeof StationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/station_/$id_/map': {
      id: '/station_/$id_/map'
      path: '/station/$id/map'
      fullPath: '/station/$id/map'
      preLoaderRoute: typeof StationIdMapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SafetyRoute: SafetyRoute,
  StationsRoute: StationsRoute,
  StationIdRoute: StationIdRoute,
  StationIdMapRoute: StationIdMapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
